### PR TITLE
Issue-87: Swagger: path definition ignored when unit returned in 2xx response

### PR DESCRIPTION
**Pull request by mbryzek**

### CODE REVIEW

**Review by JennyLeahy — COMMENTED** [review]
This PR looks good to me. I suppose the generator should pick up this placeholder model and make sure the return value is unit?

**Comment by mbryzek** [comment]
> This PR looks good to me. I suppose the generator should pick up this placeholder model and make sure the return value is unit?

Yes - exactly - we end up with a resource 'placeholder' that has the operation exposed - that operation continues to return unit.

Have a bit more to do on the tests here - and then would appreciate post merge if you could help us verify this works as expected

**Comment by JennyLeahy** [comment]
> Have a bit more to do on the tests here - and then would appreciate post merge if you could help us verify this works as expected

Sure!

**Comment by mbryzek** [comment]
@JennyLeahy this is now merged and deploying. Appreciate if you could verify when you have a moment

**Comment by JennyLeahy** [comment]
Hi @mbryzek I tested with some simple swagger definitions and it seems working. The placeholder resource is shown on the interface and the endpoints return unit in the generated client (http4s is what I've checked). However, when I upload the originally already uploaded swagger file (where previously path with unit response silently ignored), I got following error: `java.lang.RuntimeException: Multiple models found for path: io.swagger.models.Path@20a7793a: io.swagger.models.properties.RefProperty@f957c8f8, io.swagger.models.properties.RefProperty@c1748f45` The swagger file has been validated in app.swaggerhub.com. I'll see if I can narrow down which part of the file is causing the issue.

**Pull request merged**
