### PR TITLE
Updated CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by LappleApple**
Copy-pasted the text from the Gilt repo and edited.

### CODE REVIEW

**Comment by mbryzek** [comment]
thanks Lauri! going to get a bit more feedback from the core team and also we'll need to add a maintainers file as referenced if we proceed

**Comment by LappleApple** [comment]
Sure, @mbryzek. :)

**Comment by LappleApple** [comment]
Hey, how's it going with this PR? :)

**Comment by mbryzek** [comment]
closing due to age

**Pull request closed without merging**
